### ISSUE TITLE
Instructions to use?

### ISSUE THREAD

**Issue by nachazo** [blakebjorn/CardScryer#2]
Hello!
There are any possibility for get instructions to get running the application?

I have no experience with Python, I tried with 2.7, .whl, .egg... and no way, so many things that I don't know :P
For sure must be just installing and running correctly :)

Many many thanks! :D

**Comment by blakebjorn** [comment]
Install python 2.7
Download appropriate openCV 3.0/3.1 (x64/x86) - http://opencv.org/downloads.html
Drop cv2.pyd into python/lib/site-packages
open command prompt/terminal
pip install PySide PIL imagehash pandas numpy
python [path to card scryer.py]
